export const portfolioData =  [
  {
    id: 1,
    category: 'graving',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 2,
    category: 'cutting',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 3,
    category: 'cutting',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 4,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 5,
    category: 'graving',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 6,
    category: 'cutting',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 7,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 8,
    category: 'cutting',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 9,
    category: 'cutting',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 10,
    category: 'graving',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 11,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 12,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 13,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 14,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 15,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  },
  {
    id: 16,
    category: 'design',
    src: '/shoes-laser-cutting-service.jpg',
    width: "400",
    height: "400",
  }
];